# Customize server port
server:
  port: 8998

# import secret.properties
spring:
  config:
    import: secrets.properties

  # PostgresSQL Connection Settings
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  # JPA Settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
      format_sql: true

